version: '3.9'
services:

  db:
    container_name: stud_cw_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    image: postgres:14-alpine
    networks:
      - network
    ports:
      - ${HOST_DB_PORT}:${DB_PORT}
    volumes:
      - stud_cw_db_data:/var/lib/postgresql/data

  migration:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: stud_cw_migration
    entrypoint: ["make", "migrate-up"]
    depends_on:
      - db
    env_file:
      - ${ENV_FILE}
    networks:
      - network

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: stud_cw_backend
    entrypoint: ["make", "run"]
    depends_on:
      - db
      - migration
    env_file:
      - ${ENV_FILE}
    networks:
      - network
    ports:
      - ${HOST_ADMIN_PORT}:${ADMIN_PORT}
      - ${HOST_BACKEND_PORT}:${BACKEND_PORT}

networks:
  network:
    driver: bridge

volumes:
  stud_cw_db_data:
