"""add_order

Revision ID: 2476084b3866
Revises: 726c7b4f7a59
Create Date: 2022-10-16 18:25:34.122674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2476084b3866'
down_revision = '726c7b4f7a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.FetchedValue(), nullable=True),
    sa.Column('shipment_cost', sa.Float(), nullable=False),
    sa.Column('shipment_at', sa.DateTime(), nullable=False),
    sa.Column('status', postgresql.ENUM('processing', 'transiting', 'delivered', name='order_status', create_type=False), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_table('orderproduct',
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    op.create_index(op.f('ix_orderproduct_order_id'), 'orderproduct', ['order_id'], unique=False)
    op.create_index(op.f('ix_orderproduct_product_id'), 'orderproduct', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderproduct_product_id'), table_name='orderproduct')
    op.drop_index(op.f('ix_orderproduct_order_id'), table_name='orderproduct')
    op.drop_table('orderproduct')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
