"""add_role

Revision ID: 6406de4e4833
Revises: 
Create Date: 2022-10-16 18:18:05.004242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6406de4e4833'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    role = postgresql.ENUM('user', 'manager', name='role')
    role.create(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    role = postgresql.ENUM('user', 'manager', name='role')
    role.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
