"""add_order_status

Revision ID: 726c7b4f7a59
Revises: c01782220208
Create Date: 2022-10-16 18:22:55.082521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '726c7b4f7a59'
down_revision = 'c01782220208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    order_status = postgresql.ENUM('processing', 'transiting', 'delivered', name='order_status')
    order_status.create(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    order_status = postgresql.ENUM('processing', 'transiting', 'delivered', name='order_status')
    order_status.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
