"""add_feedback

Revision ID: c01782220208
Revises: d471a0127551
Create Date: 2022-10-16 18:22:28.227752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c01782220208'
down_revision = 'd471a0127551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', postgresql.UUID(as_uuid=True),
              server_default=sa.text('gen_random_uuid()'),
              nullable=False),
    sa.Column('created_at', sa.DateTime(),
              server_default=sa.FetchedValue(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True),
              nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True),
              nullable=False),
    sa.CheckConstraint('mark >= 1 AND mark <= 5',
                       name='mark_check'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'],
                            ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'],
                            ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_product_id'), 'feedback', ['product_id'],
                    unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_product_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
